language: python

python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin

install:
    - pip install --upgrade tox tox-travis

script: tox
